package problemDomain.accounts;

import exceptions.IllegalEmailException;
import exceptions.IllegalNameException;

/**
 * @author Ryan Young, Sean Allen, Scott Bolstad, Tyler Power
 * @version 1.0
 *
 * Class description: This an implementation of the Account Type
 * Object with Magician privileges in our system.
 * Will be the main user of the system, and responsible for maintaining shows, prices, tricks, and client Lists
 * Also will be able to view the reports generated by the report classes.
 */
public class MagicianAccount extends Account
{

	//Constants
	//Attributes
	//Constructors
	
	/**
	 * Constructor for the Magician Accounts of our System.
	 * @param id the database id of the Account
	 * @param name the name of the Account
	 * @param email the email of the Account
	 * @throws IllegalNameException 
	 * @throws IllegalEmailException 
	 */
	public MagicianAccount(int id, String name, String email) throws IllegalArgumentException, IllegalNameException, IllegalEmailException
	{
		super(id, name, email);
		
	}
	
	//Getter and Setter Methods
	//Operational Methods
	
}
